sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_795a83ea4be5_key -iv $encrypted_795a83ea4be5_iv -in travis_deployer_sa.json.enc -out travis_deployer_sa.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json