apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: example-multi-com-tls
spec:
  secretName: example-multi-com
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: example-multi.com
  dnsNames:
    - example-multi.com
    - www.example-multi.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - example-multi.com
          - www.example-multi.com